add scrapper for fda drugs and restructure directory
codexstanford/cardinal-care-dev pull request #13
Opened 2024-03-06 23:22 UTC by harshitgupta412

2024-03-07 20:34 UTC, labhinav commented
Does this link with the logic program?

2024-03-07 20:37 UTC, harshitgupta412 commented
> Does this link with the logic program?

Not yet. FDA Drugs are not yet used in the logic. FDA contraceptives are but rn they are generated in a different file instead of cardinal_care.hrf.

2024-03-07 23:55 UTC, labhinav commented
Are there test cases for fda contraceptives?

2024-03-14 09:14 UTC, harshitgupta412 commented
> Are there test cases for fda contraceptives?

yes

2024-03-14 18:28 UTC, labhinav requested changes

2024-03-14 18:28 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  leq(min_age, M) & leq (M, max_age) &
I don't think leq should be used with uninitialized variables, ideally we should initialize them first then run leq to check if they are valid

2024-03-14 18:28 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  claim.previous_vaccines_flu_more_than_2(Prev_Count) &
we should update documentation to make it clear that this is annual count

2024-03-14 18:36 UTC, harshitgupta412 commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  claim.previous_vaccines_flu_more_than_2(Prev_Count) &
the Prev_count is not annual. It is lifetime.

2024-03-14 18:36 UTC, harshitgupta412 commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  claim.previous_vaccines_flu_more_than_2(Prev_Count) &
vaccine dose count is still annual as per the schema

2024-03-14 18:44 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  claim.previous_vaccines_flu_more_than_2(Prev_Count) &
vaccine dose count used elsewhere is not annual, this should be a separate field in that case

2024-03-14 18:48 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  leq(min_age, M) & leq (M, max_age) &
What are min_age and max_age here?

2024-03-14 19:01 UTC, harshitgupta412 commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  leq(min_age, M) & leq (M, max_age) &
similar to general vaccine clauses. check if the current age is in some range and that range has a corresponding limit.

2024-03-14 19:13 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  age_range_limit_flu(C,N,min_age,max_age,Prev_Count) &
Shouldn't min_age and max_age be variables?

2024-03-14 19:13 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +  age_range_limit_flu(C,N,min_age,max_age,Prev_Count) &
Are all test cases passing?

2024-03-14 21:28 UTC, labhinav requested changes

2024-03-14 21:28 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.hrf
> +age_range_limit_flu(C,2,6,96,no).
Why just 200? A person could be much older than 200 months

2024-03-14 21:42 UTC, labhinav commented
also can you add person.immunocompromised to schema

2024-03-16 21:56 UTC, labhinav approved these changes

2024-03-16 21:56 UTC, labhinav commented
Please create PR to main as well

2024-03-16 21:57 UTC, merged