update cardinal care rules and ui
codexstanford/cardinal-care-dev pull request #7
Opened 2024-02-02 08:36 UTC by labhinav

2024-02-02 20:09 UTC, pjames27 requested changes
There are some things that I'm happy with being on your dev branch, but would prefer not go into main. In my requested changes below, when I mention "don't push" something, feel free to keep them on your dev branch.
Going forward, I'm happy to review your PR's more frequently to give you a better idea of what I'm expecting. (E.g. I'll be somewhat particular about making changes to files everyone is using, such as epilog.js and load_common_data.js.)

If you have any questions, do let me know.

Requesting the following changes:
- Don't push the .ds_store files
- Don't push the changes to chubb_hospital_cash.js
- Update index.js to generate a link to your cardinal care page
- See comment in "cardinal_care.html"
- Don't push changes to epilog.js, even if it's just encoding or formatting
- See comment on load_common_data.js
- Please rename "load_example_claim.js" or move to another folder (e.g. "src/{abhinav,harshit}dev/", "src/{abhinav,harshit}-utils/", or "src/dev-utils/"), or leave on dev branch. I think the file is useful for development and you should use it, but it shouldn't be in src for general use unless it's either more generalized, or it's used in our public-facing version of the site.

2024-02-04 19:38 UTC, labhinav commented on src/load_common_data.js
> +module.exports = {load_common_data};
Acknowledged.

2024-02-04 19:38 UTC, labhinav commented on claims_analysis/cardinal_care/cardinal_care.html
> +    <a href="../../index.html">Cardinal Care</a>
Fixed

2024-02-04 19:59 UTC, labhinav commented
Thanks for the comments, I've resolved them . Will pay more attention on what goes into PRs going forward

2024-02-05 01:44 UTC, merged